/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloCpp */

#ifndef _Included_HelloCpp
#define _Included_HelloCpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloCpp
 * Method:    callCpp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloCpp_callCpp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
